kind: pipeline
name: Kernel Compile
clone:
  depth: 50
steps:
 - name: compile
   image: diazaji/python:kernel
   environment:
     TELEGRAM_TOKEN:
       from_secret: TELEGRAM_TOKEN
   commands:
      - cd /drone/src
      - bash build.sh 10
